### ISSUE TITLE
Question on inventory management

### ISSUE THREAD

**Issue by stephanstapel** [gebirgslok/BricklinkSharp#10]
Hi,

sorry for yet another usage question, I hope that this is alright for you.

digging through the inventory management API I found that updating inventory only allows to add/substract from stock, i.e. setting deltas, not set absolute stock quantity. Did you come across this by yourself and did you solve this for yourself?

**Comment by gebirgslok** [comment]
Heyho,

the Bricklink API documentation states:
_quantity (has to have a + (plus) or - (minus) sign in front of it. You can only add or subtract quantity, not set it to a new value because quantity can change when buyers submit orders in your store.)_ (see also https://www.bricklink.com/v3/api.page?page=update-inventory).
I think thats reasonable from a backend point of view.

You can do something like

```
UpdateInventoryQuantity(absoluteValue){
  1) getCurrentQuantity
  2) delta = absoluteValue - currentValue
  3) call the bricklink API with the delta
}
```

However, *if* someone places an order withing the few milliseconds between 1) and 3) your App will get out of sync.

Hope that helps.
BR Jens

**Comment by stephanstapel** [comment]
Thanks! Yep, that is how I implemented it now. Concerning 'backend': depends on what the backend is. If it is my application, the bricklink inventory would just be a mirror.
