### ISSUE TITLE
UpdatePaymentStatusAsync expects wrong HTTP status code

### ISSUE THREAD

**Issue by Fandermill** [gebirgslok/BricklinkSharp#7]
Hi there!

Thank you for the great work on the client, it works without hassle so far. But now I do run into a problem...

When I update a payment status through the `IBricklinkClient.UpdatePaymentStatusAsync` method, I get a `BricklinkHttpErrorException` telling me that status code 200 was expected, but 204 was received.

I checked the source code and I found that the method is using the `PutEnsureNoResponseDataAsync` extension method, which in turn states that it expects the 200 status code.

I'm no expert in the Bricklink API and I'm not sure there are any endpoints that respond with a 200 for a PUT request. I can't change the expected code to 204 without knowing this, otherwise I would have submitted a PR.

Hope you can help!

**Comment by gebirgslok** [comment]
Heyho,

thanks for reporting this issue. 

There are 3 endpoints the `PutEnsureNoResponseDataAsync` is used for:
- `UpdateOrderStatusAsync`
- `UpdatePaymentStatusAsync`
- `SendDriveThruAsync`

Do you have the possibility to check whether they all return **204**? Currently I don't have access to active orders.
I remember that the API had some inconsistencies when I wrote this lib. It might be that some endpoints return 200 while others return 204.

If all (3) endpoints return 204 then the expectedCode can simply be replaced. Otherwise the expectedCode must be passed to the `PutEnsureNoResponseDataAsync`.

As a rapid workaround you can do the following:

```csharp
        try
        {
            await client.UpdatePaymentStatusAsync(orderId, status);
        }
        catch (BricklinkHttpErrorException e)
        {
            if (e.ReceivedCode != 204)
            {
                throw e;
            }
        }
```
