### ISSUE TITLE
Thoughts about the API call rate limit

### ISSUE THREAD

**Issue by stephanstapel** [gebirgslok/BricklinkSharp#9]
Hi,

I was just wondering if you have any thoughts about the API call rate limit of 5,000 calls per day on Bricklink. Are you measuring the calls in your own application or are you just ignoring this limit?

**Comment by gebirgslok** [comment]
Hi,

currently I measure the limits in my app. The limit is AFAIK soft, so you can make more than 5000 calls on a single day but on the average the limit should not be exceeded. 

I have some WIP for a mechanism to add callbacks for every request so that every user can implement their own counting strategy (some want to persist to a DB, others on a file, ...). But don't know when it's ready to be released.

**Comment by stephanstapel** [comment]
Such a feature would be of great value!
If you need assistance, let me know!
